# Generated by Django 5.2.6 on 2025-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_payslip_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
