# Generated by Django 5.2.6 on 2025-09-21 10:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_dob_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='payslips/'),
        ),
    ]
