# Generated by Django 5.2.3 on 2025-12-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_payslip_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(max_length=25),
        ),
    ]
